---
- name: Create ISO_5AC_LMNET-010-ZAH-274N $ or update
  zabbix_host:
    server_url: "{{ server_url }}"
    login_user: "{{ lookup('env','ZABBIX_USER') }}"
    login_password: "{{ lookup('env','ZABBIX_PASSWORD') }}"
    host_name: ISO_5AC_LMNET-010-ZAH-274N
    visible_name: ISO_5AC_LMNET-010-ZAH-274N
    host_groups:
     - UBNT_sektor
    link_templates:
     - ICMP Ping
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: 10.153.70.37
        port: "10050"
